export enum ContentType {
    JSON = "application/json",
    XML = "application/xml",
    HTML = "text/html",
    PLAIN_TEXT = "text/plain",
    CSS = "text/css",
    JAVASCRIPT = "application/javascript",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    MULTIPART_FORM_DATA = "multipart/form-data",
    PNG = "image/png",
    JPEG = "image/jpeg",
    GIF = "image/gif",
    BMP = "image/bmp",
    WEBP = "image/webp",
    SVG = "image/svg+xml",
    PDF = "application/pdf",
    ZIP = "application/zip",
    GZIP = "application/gzip",
    OCTET_STREAM = "application/octet-stream",
    CSV = "text/csv",
    RTF = "application/rtf",
    MP3 = "audio/mpeg",
    MP4 = "video/mp4",
    OGG_AUDIO = "audio/ogg",
    OGG_VIDEO = "video/ogg",
    WEBM_AUDIO = "audio/webm",
    WEBM_VIDEO = "video/webm"
}
